### ISSUE TITLE
[FIRMWARE] Autentykacja

### ISSUE THREAD

**Issue by whoamipl** [whoamix/team-project#16]
Dodanie prostej autentykacji. Można zroibić tak, ze w requescie będzie jakis token z serwera/apki, i będzie porównywany jako zwykływ string.

**Comment by mtkaczyk** [comment]
The ESP8266WebServer class allows only to do simple auth by comparing.
It compares sent values with expected.

Should be easy to implement.

**Comment by mtkaczyk** [comment]
https://github.com/whoamix/team-project/pull/17
