### ISSUE TITLE
[SERVER] Dodanie kontrolerów.

### ISSUE THREAD

**Issue by whoamipl** [whoamix/team-project#20]
Ten task polega na dodaniu endpointów do przyjmowania zapytań od aplikacji i wysyłaniu ich do włącznika.
Proponowane endpointy:

### Status
----
  Zwraca jsona z polem status.

* **URL**

  /status/:switchid? 

* **Method:**

  `GET`
  
*  **Prarametry*

   `swithid=[integer]`

* **Poprawna odpowiedź:**

  * **Code:** 200 <br />
    **Content:** `{ status: ENUM_SWITCH_STATUS " }`
 
* **Error Response:**

  * **Code:** 404 NOT FOUND <br />
    **Content:** `{ error : "Can't obtain switch status" }`

### Toggle
----
  Zmienia stan włącznika.

* **URL**

  /toggle/:switchid? 

* **Method:**

  `GET`
  
*  **Prarametry*

   `swithid=[integer]`

* **Poprawna odpowiedź:**

  * **Code:** 200 <br />
 
* **Error Response:**

  * **Code:** 404 NOT FOUND <br />
  *Content:** `{ status: ENUM_SWITCH_STATUS " }`

### On
----
  Zwraca jsona z polem status.

* **URL**

  /on/:switchid? 

* **Method:**

  `GET`
  
*  **Prarametry*

   `swithid=[integer]`

* **Poprawna odpowiedź:**

  * **Code:** 200 <br />
    **Content:** `{ status: ENUM_SWITCH_STATUS " }`
 
* **Error Response:**

  * **Code:** 404 NOT FOUND <br />
 **Content:** `{ error : "Can't change switch state" }`

### Off
----
  Zwraca jsona z polem status.

* **URL**

  /off/:switchid? 

* **Method:**

  `GET`
  
*  **Prarametry*

   `swithid=[integer]`

* **Poprawna odpowiedź:**

  * **Code:** 200 <br />
    **Content:** `{ status: ENUM_SWITCH_STATUS " }`
 
* **Error Response:**

  * **Code:** 404 NOT FOUND <br />
    **Content:** `{ error : "Can't obtain switch status" }`

---
Po wysłaniu requesta do włącznika, wysyłamy kolejnego, aby sprawdzić jego stan, a następnie wysyłamy stan do kliena jako respone. 
1. Odebranie requesta od klienta
2. Wysłanie komendy do włacznika
3. Odebranie response od włacznika
4. Jeśli ok to pytamy o status, jeślnie to wysyłamy 404
5. Jeśli zapytaliśmy o status, to dopiero wysyłamy response

**Comment by whoamipl** [comment]
A może zrobić tak, aby włącznik wysyłał info po wykonaniu akcji na nim? Zapraszam do dyskusji

**Comment by mtkaczyk** [comment]
Toggle wystarczy nie potrzebujemy oddzielnie On i OFF.
Po wykonaniu akcji wlącznik zwraca swój stan w odpowiedzi, wydaje mi się że nic wiecej nie potrzeba.

**Comment by olekkosma** [comment]
Dodanie obslugi wyjatku w momencie braku odpowiedzi od sonof. Najlepiej zwracac inny komunikat zamiast on i off, zrobic trzeci, ktory na froncie sie przechwyci. Trzeci status musi byc pod /toggle i pod /status
